---
title: "Test survey index standardization with spatiotemporal model"
author: "Sean C. Anderson"
date: "2018-03-27"
output:
  html_document
---

```{r knitr-opts, echo = FALSE, cache=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  cache = TRUE,
  autodep = TRUE,
  fig.path = "inla-figs/",
  cache.path = "inla-cache/"
)
```

```{r package-prep, message=FALSE, warning=FALSE, cache=FALSE}
library(dplyr)
library(ggplot2)
library(gfplot)
library(dplyr)
library(INLA)
source("fit-inla.R")
```

Start by reading in the data:

```{r get-data, eval=FALSE}
d_survey_sets <- get_survey_sets("pacific cod")
```

```{r local-load, echo=FALSE, eval=TRUE, include=FALSE, cache=FALSE}
# d_survey_sets <- readRDS("../gfplot/inst/pcod-cache/pbs-survey-sets.rds")
d <- readRDS("~/src/gfsynopsis/report/data-cache3/pacific-cod.rds")
d_survey_sets <- filter(d$survey_sets, survey_abbrev %in% c("SYN WCVI", "SYN QCS", "SYN HS", "SYN WCHG"))
```

Set which survey we want:

```{r survey-selection, cache=FALSE}
# survey <- "Queen Charlotte Sound Synoptic Survey"
survey_short <- c("SYN WCVI", "SYN WCHG", "SYN HS", "SYN QCS")
```

Prepare data and create prediction grid:

```{r data-prep, cache=FALSE}
d <- plyr::ldply(survey_short, function(x) {
  data.frame(gfplot:::tidy_survey_sets(d_survey_sets,
    survey = x,
    years = 2000:2017
  ), survey = x, stringsAsFactors = FALSE)
}) %>% as_data_frame()

sum(is.na(d$depth))
d <- d[!is.na(d$depth), , drop = FALSE]
d <- gfplot:::scale_survey_predictors(d)
head(d)

fake_yrs <- data.frame(year = sort(unique(d$year)), fake_year = seq_along(unique(d$year)))
d <- inner_join(d, fake_yrs, by = "year")
# d$X <- d$X / 10 # for computational purposes
# d$Y <- d$Y / 10 # for computational purposes

dat <- rename(d, orig_year = year, year = fake_year)

pg <- plyr::ldply(survey_short, function(x) {
  gfplot:::make_prediction_grid(filter(d, year %in% c(2016, 2017)), survey = x)$grid
})
cell_area <- gfplot:::make_prediction_grid(filter(d, year %in% c(2016, 2017)), survey = survey_short[[1]])$cell_area
# pg <- pg_out$grid
# pg$X <- pg$X / 10
# pg$Y <- pg$Y / 10
```

Fit models:

```{r inla-fit, message=FALSE, warning=FALSE, results='hide'}
m_inla_bin <- fit_inla2(dat,
  response = "present", fit_model = T,
  max_edge = c(60, 120),
  family = "binomial", plot = TRUE, include_depth = TRUE,
  offset = c(25, 50), cutoff = 40
)

dpos <- filter(dat, present == 1)
dpos$density <- dpos$density * 1e3 # for computational purposes; too small otherwise
m_inla_pos <- fit_inla2(dpos,
  response = "density", fit_model = T,
  family = "gamma", plot = TRUE, include_depth = TRUE,
  max_edge = c(60, 120),
  offset = c(25, 50), cutoff = 40
)
```

Draw from posterior and project onto grid:

```{r posterior-draws}
pg_one_year <- filter(pg, year == min(pg$year))
p_bin <- predict_inla(m_inla_bin, pred_grid = pg_one_year, samples = 200, include_depth = FALSE)
p_pos <- predict_inla(m_inla_pos, pred_grid = pg_one_year, samples = 200, include_depth = FALSE)
```

Calculate probability * Gamma median values on the grid:

```{r prediction-grid-calcs}
out <- stats::plogis(p_bin) * exp(p_pos)
out_median <- apply(out, c(1, 3), median)

pg_all <- bind_rows(replicate(dim(p_bin)[3], pg_one_year, simplify = FALSE))
pg_all$year <- rep(fake_yrs$year, each = nrow(pg_one_year))
out_long <- reshape2::melt(out_median)
pg_all$pred <- out_long$value
```

Spatiotemporal plot:

```{r spatio-temporal-plot, fig.width=9, fig.height=9}
coast <- gfplot:::load_coastline(range(d$lon), range(d$lat), utm_zone = 9)
isobath <- gfplot:::load_isobath(range(d$lon), range(d$lat),
  bath = c(100, 200, 500), utm_zone = 9
)
map_padding <- c(-5, 5)

g <- ggplot(pg_all, aes(X * 10, Y * 10)) +
  geom_raster(aes(fill = sqrt(pred))) +
  scale_fill_viridis_c(option = "C") +
  facet_wrap(~ year) +
  geom_polygon(
    data = coast, aes_string(x = "X", y = "Y", group = "PID"),
    fill = "grey80"
  ) +
  geom_point(
    data = filter(d, present == 1),
    aes(x = X * 10, y = Y * 10, size = density), inherit.aes = FALSE,
    pch = 21, col = "white", alpha = 0.3
  ) +
  geom_point(
    data = filter(d, present == 0),
    aes(x = X * 10, y = Y * 10), inherit.aes = FALSE,
    pch = 4, col = "white", alpha = 0.2
  )

g <- g + geom_path(
  data = isobath, aes_string(
    x = "X", y = "Y",
    group = "paste(PID, SID)"
  ),
  inherit.aes = FALSE, lwd = 0.4, col = "grey70", alpha = 0.4
)

g <- g + xlab("UTM 9N Easting (km)") + ylab("UTM 9N Northing (km)") +
  scale_size(range = c(0, 9)) +
  guides(size = FALSE, fill = FALSE) +
  theme_pbs() +
  coord_equal(
    expand = FALSE, xlim = range(pg_all$X * 10) + map_padding,
    ylim = range(pg_all$Y * 10) + map_padding
  )

print(g)
```

Annual index plot:

```{r violin-plot}
yr_est <- apply(out, c(2, 3), sum)
yr_est <- reshape2::melt(yr_est) %>%
  rename(i = Var1, fake_year = Var2) %>%
  inner_join(fake_yrs, by = "fake_year")

ggplot(yr_est, aes(as.factor(year), value * 1e3 * cell_area)) +
  geom_violin() +
  theme_pbs() +
  ylim(0, NA)
```

Calculate bootstrapped design-based index:

```{r boot}
surv <- d_survey_sets %>%
  filter(survey_series_desc == survey) %>%
  select(-sample_id) %>%
  unique()

calc_bio <- function(dat, i = seq_len(nrow(dat))) {
  dat[i, , drop = FALSE] %>%
    group_by(year, survey_id, area_km2, grouping_code) %>%
    summarise(density = mean(density_kgpm2 * 1e6)) %>%
    group_by(year) %>%
    summarise(biomass = sum(density * area_km2)) %>%
    pull(biomass)
}

boot_biomass <- function(dat, reps = 1000) {
  out <- dat %>%
    group_by(year, species_common_name, survey_series_desc) %>%
    do({
      b <- boot::boot(., statistic = calc_bio, strata = .$grouping_code, R = reps)
      suppressWarnings(bci <- boot::boot.ci(b, type = "perc"))
      dplyr::tibble(
        mean_boot = mean(b$t),
        median_boot = median(b$t),
        lwr = bci$percent[[4]],
        upr = bci$percent[[5]],
        cv = sd(b$t) / mean(b$t),
        biomass = calc_bio(.)
      )
    })
}

out_boot <- boot_biomass(surv)
```

Compare:

```{r ribbon-plot, fig.width=9}
yr_est_summ <- group_by(yr_est, year) %>%
  summarise(
    lwr = quantile(value * 1e3 * cell_area, probs = 0.025),
    upr = quantile(value * 1e3 * cell_area, probs = 0.975),
    biomass = quantile(value * 1e3 * cell_area, probs = 0.5)
  ) %>%
  mutate(type = "spatiotemporal")

both <- bind_rows(
  yr_est_summ,
  mutate(out_boot, type = "design-based bootstrap")
)

ggplot(both, aes(as.numeric(year), biomass,
  colour = type,
  fill = type, ymin = lwr, ymax = upr
)) +
  geom_ribbon(alpha = 0.2, lwd = 0) +
  geom_line(lwd = 1) +
  theme_pbs() +
  ylim(0, NA) +
  scale_fill_manual(values = c("#474747", "#2188ff")) +
  scale_colour_manual(values = c("#474747", "#2188ff")) +
  ylab("Biomass") + xlab("Year") +
  labs(fill = "Type", colour = "Type")
```

